
id = "Webleashing"
name = "webleashing"
description = "leash ur oomfs <3"
version = "1.0.0"
homepage = "https://github.com/barzamin/webleashing"
author = "3moon"

icon = "icon.png"
readme = "README.md"

[project]
csharp = "./Webleashing/Webleashing.csproj"
godot = "./project/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.14"

[[dependencies]]
id = "Sulayre.Lure"
thunderstore_version = "Sulayre-Lure-4.2.1"
